### PR TITLE
fix Wall-thermostat

### PR DESCRIPTION
**Pull request by bowao**
#28

### CODE REVIEW

**Comment by Apollon77** [comment]
Good catch ;-) I will merge next week when back from vacation.

**Comment by bowao** [comment]
Please wait with the merge, there is something else to correct. See Issue #30 .
I'm just waiting for feedback.

**Comment by bowao** [comment]
Closed. See pullrequest #31 and issue #30

**Comment by Apollon77** [comment]
Perfect ;-)

**Pull request closed without merging**
